### PR TITLE
feat: Add persistence settings by JSON API

### PR DESCRIPTION
**Pull request by chenjr0719**
Hi @BoltManGuy, thanks for your great effort to build this fantastic mod. I would like to add a minor feature to improve it hope you don't mind.

Starting from the REFramework 1.1.1, we can use the [JSON API](https://github.com/praydog/REFramework/wiki/json) to have persistence settings by writing a config JSON. I have made some changes to your mod to support this feature. Please check my changes and let me know your idea about them. 🙏

### CODE REVIEW

**Review by Bolt-Scripts — APPROVED** [review]
nice that i don't have to figure this out, thanks.
though i hate that "if changed" statement after every UI call. 
I wish their imgui api had a "BeginChangeCheck"

**Comment by chenjr0719** [comment]
Thank you @BoltManGuy , I also hate the current implementation to check and save changes. 😂 I think maybe we can simplify it by using only one if changed check to save all the settings. 🤔

**Comment by Bolt-Scripts** [comment]
Best I can think to do is do like keep a master changed value and do "anyChanged = anyChanged or changed"
Then can save only once at the end.
But idk enough about lua or this api to know if its possible to one-line each thing because it annoyingly returns a tuple.

**Comment by Bolt-Scripts** [comment]
Went ahead and cleaned it up with a small update I did to make the settings nicer now.
Saw there was a function specifically for saving config that gets called when REF wants to save and decided it was better to save there and remove all the individual checks.

**Pull request merged**
